name: Node.js CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt update
          # chromium dependencies
          npx playwright-chromium install-deps chromium
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - name: Lint
        run: |
          npx tsc --noEmit
          npx prettier --check .
      - run: npm run build
      - run: npm test
        env:
          # Used by chalk. Ensures output from Jest includes ANSI escape
          # characters that are needed to match test snapshots.
          FORCE_COLOR: true
      - run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
